#!/bin/bash
### BEGIN INIT INFO
# Provides: zram
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

NRDEVICES=$(grep -c ^processor /proc/cpuinfo | sed 's/^0$/1/')

start() {
if modinfo zram | grep -q ' zram_num_devices:' 2>/dev/null; then
  MODPROBE_ARGS="zram_num_devices=${NRDEVICES}"
elif modinfo zram | grep -q ' num_devices:' 2>/dev/null; then
  MODPROBE_ARGS="num_devices=${NRDEVICES}"
else
  exit 1
fi
modprobe zram $MODPROBE_ARGS
modprobe lz4 lz4_compress

# Calculate memory to use for zram (1/5 of ram)
TOTALMEM=`LC_ALL=C free | grep -e "^Mem:" | sed -e 's/^Mem: *//' -e 's/  *.*//'`
ZMEM=$((TOTALMEM / 1024 / 5))
# Limit to 2048M
if [ ${ZMEM} -gt 2048 ]; then
  ZMEM=2048
fi
MEM=$((ZMEM / ${NRDEVICES}))

# initialize the devices
for i in $(seq ${NRDEVICES}); do
  DEVNUMBER=$((i - 1))
  echo lz4 > /sys/block/zram${DEVNUMBER}/comp_algorithm
  echo ${MEM}M > /sys/block/zram${DEVNUMBER}/disksize
  mkswap /dev/zram${DEVNUMBER}
  swapon -p 1 /dev/zram${DEVNUMBER}
done
}

stop() {
# Switching off swap
for i in $(seq ${NRDEVICES}); do
  DEVNUMBER=$((i - 1))
  swapoff /dev/zram${DEVNUMBER}
  echo 1 > /sys/block/zram${DEVNUMBER}/reset
  wait
done

sleep 2
modprobe -r zram
}

case "$1" in
start)
start
;;

stop)
stop
;;

restart)
stop
sleep 3
start
;;
*)

echo "Usage: $0 {start|stop|restart}"
RETVAL=1
esac
exit $RETVAL

